In [ ]:
"""Question 1

Write a Python program to convert an array to an ordinary list with the same items.

We can use the np.tolist() function"""

In [1]:
import numpy as np

arr1=np.array([1,2,3])
list1=arr1.tolist()
print(list1)

[1, 2, 3]


In [ ]:
"""Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: There are two possible methods to solve this problem: 

Manually (without direct function). 
Using the trace function"""

In [4]:
import numpy as np

n_array=np.array([[10,20,30],
                 [35,18,26],
                 [18,60,43]])

print("numpy matrix is :")
print(n_array)

trace = np.trace(n_array)

print(trace)


numpy matrix is :
[[10 20 30]
 [35 18 26]
 [18 60 43]]
71


In [ ]:
"""Question 3

Given an array of your choice, get all the values higher than X:

If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2"""

In [5]:
import numpy as np
x = np.array([[1,2],[3,5]])
print("Original array: ")
print(x)
print("Values bigger than 2 =", x[x>2])
print("Their indices are ", np.nonzero(x > 2))

Original array: 
[[1 2]
 [3 5]]
Values bigger than 2 = [3 5]
Their indices are  (array([1, 1]), array([0, 1]))


In [ ]:
"""Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array"""

In [8]:
import numpy as np
A = np.array([4, 10, 20])
B = np.array([4, 10, 20])
A + B


array([ 8, 20, 40])

In [ ]:
"""Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function"""

In [10]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(1, 2)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.88171458 0.31838237]]

Subtract the mean of each row of the said matrix:

[[ 0.28166611 -0.28166611]]


In [1]:
import numpy as np

a = np.random.rand(3, 4)
print(a)

"""array size is 3x4"""

b = a - a.mean(axis=1, keepdims=True)
print(b)

[[0.05136269 0.1851336  0.62848979 0.36717673]
 [0.46577613 0.44135563 0.19564136 0.82582214]
 [0.94696529 0.05074712 0.57038692 0.31512955]]
[[-0.25667801 -0.1229071   0.32044909  0.05913603]
 [-0.01637268 -0.04079319 -0.28650745  0.34367332]
 [ 0.47615807 -0.4200601   0.0995797  -0.15567767]]
